apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
#type: ExternalName
#externalName  : host.docker.internal
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  #type:  NodePort
